<?php
 /** 表情替换 */
function toFace($subject){
	$search=array(
		'[微笑]',
		'[撇嘴]',
		'[色]',
		'[发呆]',
		'[得意]',
		'[流泪]',
		'[害羞]',
		'[闭嘴]',
		'[大哭]',
		'[尴尬]',
		'[发怒]',
		'[调皮]',
		'[龇牙]',
		'[惊讶]',
		'[难过]',
		'[酷]',
		'[冷汗]',
		'[抓狂]',
		'[吐]',
		'[偷笑]',
	    '[可爱]',
		'[白眼]',
		'[傲慢]',
		'[饥饿]',
		'[困]',
		'[惊恐]',
		'[流汗]',
		'[憨笑]',
		'[大兵]',
		'[奋斗]',
		'[咒骂]',
		'[疑问]',
		'[嘘]',
		'[晕]',
		'[折磨]',
		'[衰]',
		'[骷髅]',
		'[敲打]',
		'[再见]',
		'[擦汗]',
		
		'[抠鼻]',
		'[鼓掌]',
		'[糗大了]',
		'[坏笑]',
		'[左哼哼]',
		'[右哼哼]',
		'[哈欠]',
		'[鄙视]',
		'[委屈]',
		'[快哭了]',
		'[阴险]',
		'[亲亲]',
		'[吓]',
		'[可怜]',
		'[菜刀]',
		'[西瓜]',
		'[啤酒]',
		'[篮球]',
		'[乒乓]',
		'[拥抱]',
		'[握手]',
	);
	$replace=array(
		'<img src="/Public/bbs/face/0_weixiao.gif"/>',
		'<img src="/Public/bbs/face/1_piezhui.gif"/>',
		'<img src="/Public/bbs/face/2_se.gif"/>',
		'<img src="/Public/bbs/face/3_fadai.gif"/>',
		'<img src="/Public/bbs/face/4_deyi.gif"/>',
		'<img src="/Public/bbs/face/5_liulei.gif"/>',
		'<img src="/Public/bbs/face/6_haixiu.gif"/>',
		'<img src="/Public/bbs/face/7_bizhui.gif"/>',
		'<img src="/Public/bbs/face/9_daku.gif"/>',
		'<img src="/Public/bbs/face/10_ganga.gif"/>',
		'<img src="/Public/bbs/face/11_fanu.gif"/>',
		'<img src="/Public/bbs/face/12_tiaopi.gif"/>',
		'<img src="/Public/bbs/face/13_ziya.gif"/>',
		'<img src="/Public/bbs/face/14_jingya.gif"/>',
		'<img src="/Public/bbs/face/15_nanguo.gif"/>',
		'<img src="/Public/bbs/face/16_ku.gif"/>',
		'<img src="/Public/bbs/face/17_lenhan.gif"/>',
		'<img src="/Public/bbs/face/18_zhuakuang.gif"/>',
		'<img src="/Public/bbs/face/19_tu.gif"/>',
		'<img src="/Public/bbs/face/20_touxiao.gif"/>',
	    '<img src="/Public/bbs/face/21_keai.gif"/>',
		'<img src="/Public/bbs/face/22_baiyan.gif"/>',
		'<img src="/Public/bbs/face/23_aoman.gif"/>',
		'<img src="/Public/bbs/face/24_jie.gif"/>',
		'<img src="/Public/bbs/face/25_kun.gif"/>',
		'<img src="/Public/bbs/face/26_jingkong.gif"/>',
		'<img src="/Public/bbs/face/27_liuhan.gif"/>',
		'<img src="/Public/bbs/face/28_hanxiao.gif"/>',
		'<img src="/Public/bbs/face/29_dabing.gif"/>',
		'<img src="/Public/bbs/face/30_fendou.gif"/>',
		'<img src="/Public/bbs/face/31_zhouma.gif"/>',
		'<img src="/Public/bbs/face/32_yiwen.gif"/>',
		'<img src="/Public/bbs/face/33_xu.gif"/>',
		'<img src="/Public/bbs/face/34_yun.gif"/>',
		'<img src="/Public/bbs/face/35_zhemo.gif"/>',
		'<img src="/Public/bbs/face/36_shuai.gif"/>',
		'<img src="/Public/bbs/face/37_kulou.gif"/>',
		'<img src="/Public/bbs/face/38_qiaoda.gif"/>',
		'<img src="/Public/bbs/face/39_zaijian.gif"/>',
		'<img src="/Public/bbs/face/40_cahan.gif"/>',
		
		'<img src="/Public/bbs/face/41_koubi.gif"/>',
		'<img src="/Public/bbs/face/42_guzhang.gif"/>',
		'<img src="/Public/bbs/face/43_qiudale.gif"/>',
		'<img src="/Public/bbs/face/44_huaixiao.gif"/>',
		'<img src="/Public/bbs/face/45_zuohengheng.gif"/>',
		'<img src="/Public/bbs/face/46_youhengheng.gif"/>',
		'<img src="/Public/bbs/face/47_haqian.gif"/>',
		'<img src="/Public/bbs/face/48_bishi.gif"/>',
		'<img src="/Public/bbs/face/49_weiqu.gif"/>',
		'<img src="/Public/bbs/face/50_kuaikule.gif"/>',
		'<img src="/Public/bbs/face/51_yinxian.gif"/>',
		'<img src="/Public/bbs/face/52_qinqin.gif"/>',
		'<img src="/Public/bbs/face/53_xia.gif"/>',
		'<img src="/Public/bbs/face/54_kelian.gif"/>',
		'<img src="/Public/bbs/face/55_caidao.gif"/>',
		'<img src="/Public/bbs/face/56_xigua.gif"/>',
		'<img src="/Public/bbs/face/57_pijiu.gif"/>',
		'<img src="/Public/bbs/face/58_lanqiu.gif"/>',
		'<img src="/Public/bbs/face/59_pingpang.gif"/>',
		'<img src="/Public/bbs/face/78_yongbao.gif"/>',
		'<img src="/Public/bbs/face/81_woshou.gif"/>',
	);
	return str_replace($search, $replace, $subject);
}  


