<?php
return array(
'site_url' => 'http://www.graphis.club',
'site_name' => 'GRAPHIS',
'site_keywords' => '日本女优，av视频网站，AV女优，美女图片，性感美女，美女写真，私房写真',
'static_url' => 'http://static.graphis.club',
'site_description' => 'GRAPHIS美女写真图片站｜日本女优AV女优性感美女私房套图',
'is_close_shop' => '1',
'shop_close_reason' => '网站维护中...',
'order_by' => 'price',
'order_type' => 'asc',
'list_type' => 'text',
'list_num' => '10',
'allow_refund_days' => '30',
'auto_confirm_delivery' => '',
'auto_cancel_order' => '',
'article_cate_id' => '1,2',
'hot_keywords' => '购物280，孕妈购',
'notice_limit_ip' => '',
'email_type' => '1',
'mail_nickname' => 'graphis',
'mail_smtp' => 'smtp.exmail.qq.com',
'smtp_user' => 'creditdz@188919.com',
'smtp_pwd' => 'Creditdz@2017',
'smtp_port' => '25',
'test_address' => 'happyzhlb@qq.com',
'country' => '1',
'state' => '35',
'city' => 'Champlain',
'address' => 'A.N. Deringer, Inc. 178 West Service Road',
'zipcode' => '12919',
'linkman' => 'xxxx',
'telephone' => '13333335555',
'webapp_url' => 'http://localhost/webapp/',
'webapp_name' => 'OKCHEM',
'is_close_webapp' => '1',
'webapp_close_reason' => 'OKCHEM 手机站维护中...',
);
?>